name = "Astrapack"
author = "Melody Madeline Lyons"
version = "1.0.0"
description = "A pack for the private Astrabit developer server"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "661cac654a7a0d9030879ed305b8f64e0138caf7835e16d8bff18ab8b23dacb0"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"
