name = "Astrapack"
author = "Melody Madeline Lyons"
version = "1.0.0"
description = "A pack for the private Astrabit developer server"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5b5db8b254267bf105ff6488c19289450985f7395339620ec6d005378fdf524"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"
