name = "Astrapack"
author = "Melody Madeline Lyons"
version = "1.0.0"
description = "A pack for the private Astrabit developer server"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a57b36d467311be46860cbe927319cf83dc6fbabfa9d9927143f930df4499ae1"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"
