name = "Astrapack"
author = "Melody Madeline Lyons"
version = "1.0.0"
description = "A pack for the private Astrabit developer server"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24c192476b495f76d92e9558e056ea9e367cb7b14536ea8dd905566ada5a339d"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"
